#!/usr/bin/perl -w 

use strict;

use NonameTV::ContentCache;

my( $force ) = @ARGV;

my $co = Test->new();

my $cc = NonameTV::ContentCache->new( { 
  basedir => "/tmp/test",
  callbackobject => $co,
} );

my( $dataref, $error ) = $cc->GetUrl( "http://www.holmlund.se/cc/1" );

if( defined( $dataref ) ) {
  print "Data1: $$dataref\n";
}
else {
  print "Error1: $error\n";
}

my( $dataref2, $error2 ) = $cc->GetContent( "test1", undef, $force );

if( defined( $dataref2 ) ) {
  print "Data2: $$dataref2\n";
}
elsif( defined( $error2 ) ) {
  print "Error2: $error2\n";
}

my( $dataref3, $error3 ) = $cc->GetContent( "test2", undef, $force );

if( defined( $dataref3 ) ) {
  print "Data3: $$dataref3\n";
}
elsif( defined( $error3 ) ) {
  print "Error3: $error3\n";
}

package Test;

sub new {
  my $class = ref( $_[0] ) || $_[0];

  my $self = { }; 
  bless $self, $class;

  return $self;
}

sub FilterContent {
  my $self = shift;
  my( $dataref, $chd ) = @_;

  return (\($$dataref . "asdf"), undef);
}

sub Object2Url {
  my $self = shift;
  my( $objectname, $chd ) = @_;

  my $url = "http://www.holmlund.se/cc/$objectname";
  return ($url, undef);
}

  
