#!/usr/bin/perl -w

use NonameTV::StringMatcher;

use strict;

my $m = NonameTV::StringMatcher->new();

$m->AddRegexp( qr/\btest\b/i, "test" );
$m->AddRegexp( qr/\bhello\b/i, "hello" );

print $m->Match( "This is a test." ) . "\n";
print $m->Match( "This is a hello." ) . "\n";
print $m->Match( "Hello, this is a test." ) . "\n";
print $m->Match( "This doesn't match." ) . "\n";


