#!/usr/bin/perl

use FindBin;
use lib "$FindBin::Bin/../lib";

use NonameTV::Job qw/StartJob EndJob/;
use NonameTV::Log qw/error/;
use NonameTV::Factory qw/InitLog/;

InitLog();
StartJob( "test", "test", 10 );
error( "Not ok." );
EndJob();
