#!/usr/bin/perl -w

use strict;

use IO::Scalar;
use NonameTV::Log qw/d p w f debug progress error 
                     StartLogSection EndLogSection SetVerbosity/;
use Getopt::Long;

my $opt = { verbose => 0,
            quiet =>0
	  };

my $res = GetOptions( $opt, qw/verbose+ quiet+/ );

SetVerbosity( $opt->{verbose}, $opt->{quiet} );

progress( "Progress" );
error( "Error" );
d "d";
p "p";
w "w";
f "f";
warn "warn";

StartLogSection( "Test" );
progress( "Progress" );
error( "Error" );
d "d";
p "p";
w "w";
f "f";
warn "warn";

my $message = EndLogSection( "Test" );

print "---\n$message---\n";
