#!/usr/bin/perl -w

use strict;

use IO::Scalar;
use NonameTV::Log qw/info progress error log_to_string log_to_string_result/;


NonameTV::Log::init( { LogFile => '/tmp/test.log'}, 
              ($ARGV[0] || "") eq '--verbose' );

error( "Error" );
progress( "Progress" );
info( "Information" );

my $h = log_to_string(1);

error( "Error" );
progress( "Progress" );
info( "Information" );

print "Message: " . log_to_string_result( $h );
