#!/usr/bin/perl -w

=pod

Svts websidor har radbrytningar i beskrivningarna som man bor ta hansyn till nar man parsar. Radbrytning mellan avsnittsbeskrivning och ovrig info.

=cut

use strict;

sub split_desc
{
  my( $t ) = @_;

  # Replace ... with ::.
  $t =~ s/\.\.\./::./;

  # Replace newlines with space and make sure that there is a dot
  # to mark the end of the sentence. 
  $t =~ s/\.*\s*\n\s*/. /g;

  # Split on a dot and whitespace followed by a capital letter,
  # but the capital letter is included in the output string and
  # is not removed by split. (?=X) is called a look-ahead.
  my @sent = grep( /\S/, split( /\.\s+(?=[A-ZÅÄÖ])/, $t ) );

  $sent[-1] =~ s/\.\s*$//;
  return @sent;
}

sub join_desc
{
  my $t = join( ". ", grep( /\S/, @_ ) );
  $t .= "." if $t =~ /\S/;
  $t =~ s/\.\.\.\./.../g;
  return $t;
}

while( <> )
{
  chomp;
  my @s = split_desc( $_ );
  foreach my $l (@s)
  {
    print "-$l-\n";
  }
  print join_desc( @s ) . "\n";
}
  
