#!/usr/bin/perl -w

use strict;

use FindBin;
use lib "$FindBin::Bin/../lib";

use NonameTV::FileStore;

my $fs = NonameTV::FileStore->new( { Path => "/tmp/fs" } );

my $content = "Hello";

$fs->AddFile( "p1.sr.se", "test", \$content );

my @files = $fs->ListFiles( "p1.sr.se" );
foreach my $file (@files) {
  print join( ", ", @{$file} ) . "\n";
}

$fs->RecreateIndex( "p1.sr.se" );

@files = $fs->ListFiles( "p1.sr.se" );
foreach my $file (@files) {
  print join( ", ", @{$file} ) . "\n";
}
