#!/usr/bin/perl -w

use strict;

use FindBin;
use lib "$FindBin::Bin/../lib";

use NonameTV::Factory qw/CreateFileStore/;

my $fs = CreateFileStore( "Viasat" );

my $content = "Hello";

$fs->AddFile( "p1.sr.se", "test", \$content );

my @files = $fs->ListFiles( "p1.sr.se" );
foreach my $file (@files) {
  print join( ", ", @{$file} ) . "\n";
}

$fs->RecreateIndex( "p1.sr.se" );

@files = $fs->ListFiles( "p1.sr.se" );
foreach my $file (@files) {
  print join( ", ", @{$file} ) . "\n";
}

my $cref = $fs->GetFile( "p1.sr.se", "test" );
print "Hello: $$cref\n";
