#!/bin/bash

NROOT=/var/local/nonametv
PROOT=/home/mattias/development/nonametv

h=true
d=true

cd $PROOT

if [ $1x = --weeklyx ]
then
  # Run weekly commands.
  perl -I lib tools/nonametv-remove-old
  tools/se/nonametv-import-allhttp --remove-old
  exit
fi

if [ $1x = --dailyx ]
then
  # Run daily commands
  d=
fi

if [ $1x = --hourlyx ]
then
  # Run hourly commands
  h=
fi

tools/se/nonametv-update-mark > $NROOT/xmltv_staging/last_updated

$d tools/se/nonametv-import-allhttp --quiet
$h tools/se/nonametv-import-allhttp --quiet --short-grab
$d perl -I lib tools/nonametv-import Eurosport --quiet
$d perl -I lib tools/nonametv-import Discovery_xml --quiet
tools/se/nonametv-import-allmail

$d perl -I lib/ tools/nonametv-export Xmltv --remove-old
$d perl -I lib/ tools/nonametv-export Json --remove-old

tools/se/nonametv-updatesite

# This shouldn't produce any output, but there seems to be a bug
# somewhere.
$d perl -I lib tools/nonametv-export Xmltv --force-export --verbose 2>&1 | grep -v INFO

# Update the Combiner-channels as well.
$d perl -I lib tools/nonametv-import Combiner --quiet
$h perl -I lib tools/nonametv-import Combiner --short-grab --quiet

$d perl -I lib tools/nonametv-import Timeshifter --quiet
$h perl -I lib tools/nonametv-import Timeshifter --short-grab --quiet

tools/se/nonametv-updatesite

$d tools/se/nonametv-xmltv-compare-run
perl -I lib tools/nonametv-batchlog > /srv/web/converter.xmltv.se/root/status/batchlog.html

