#!/usr/bin/perl -w

use strict;

use MIME::Parser;
use MIME::Head;
use File::Temp qw/tempdir/;
use File::Copy qw/move/;

if( scalar( @ARGV ) != 1 )
{
  print << "EOHELP";
Usage: cat mail | nonametv-mailfilter Importername

Extracts all attachments from the mail and runs nonametv-importer 
with all the files.

EOHELP

  exit 1;
}

my $importer = $ARGV[0];
my $filedir = tempdir( CLEANUP => 0 );

sub process_files 
{
  my( $ent, $imp ) = @_;

  my @parts = $ent->parts;

  if (@parts) 
  {        
    # multipart...
    map { process_files($_, $imp) } @parts;
  }
  else 
  {
    # single part...
    my $recfn = $ent->head->recommended_filename || "noname";
    move( $ent->bodyhandle->path, "$filedir/$recfn" );
    print "nonametv-import $importer '$filedir/$recfn'\n";
  }
}


my $msgdir = tempdir( CLEANUP => 1 );
print STDERR "Message: $msgdir\n";

# Create a new parser object:
my $parser = new MIME::Parser;
$parser->output_dir($msgdir);
    
my $entity = $parser->read(\*STDIN) or 
  print STDERR "Couldn't parse MIME\n";

# Congratulations: you now have a (possibly multipart) MIME entity!
process_files($entity, $importer);

