#!/bin/bash

NROOT=/var/local/nonametv
PROOT=/home/mattias/development/nonametv

cd $PROOT

getmail -q -rdiscovery.rc
getmail -q -rkanal9.rc
getmail -q -rngcsverige.rc
perl -I lib tools/se/nonametv-parse-maildir
perl -I lib tools/nonametv-import Discovery
perl -I lib tools/nonametv-import Kanal5_mail
perl -I lib tools/nonametv-import VH1
perl -I lib tools/nonametv-import KanalLokal


