#!/bin/sh

NROOT=/var/local/nonametv
SC_OPT=-qq

if [ $1z = '--verbosez' ]
then
  SC_OPT=
fi

rsync -c --delete -r $NROOT/xmltv_staging/ $NROOT/xmltv/
sitecopy --update $SC_OPT tv.swedb.se
rsync -a --delete $NROOT/xmltv/ acheron.geijersson.com:public_html/xmltv/
rsync -a --delete $NROOT/xmltv/ fiorina161.geijersson.com:public_html/xmltv/
