#!/bin/bash

NROOT=/var/local/nonametv
PROOT=/home/mattias/development/nonametv

Q="--quiet --quiet"

h=true
d=true

cd $PROOT

if [ $1x = --weeklyx ]
then
  # Run weekly commands.
  perl -I lib tools/nonametv-remove-old
  tools/se/nonametv-import-allhttp --remove-old
  exit
fi

if [ $1x = --dailyx ]
then
  # Run daily commands
  d=
fi

if [ $1x = --hourlyx ]
then
  # Run hourly commands
  h=
fi

tools/se/nonametv-update-mark > $NROOT/xmltv_staging/last_updated

$d tools/se/nonametv-import-allhttp $Q
$h tools/se/nonametv-import-allhttp $Q --short-grab
$d perl -I lib tools/nonametv-import Eurosport $Q
$d perl -I lib tools/nonametv-import Discovery_xml $Q
tools/se/nonametv-import-allmail

$d perl -I lib/ tools/nonametv-export Xmltv --remove-old
$d perl -I lib/ tools/nonametv-export Json --remove-old
$d tools/nonametv-icon-update --quiet --unattended

tools/se/nonametv-updatesite $Q

# This shouldn't produce any output, but there seems to be a bug
# somewhere.
$d perl -I lib tools/nonametv-export Xmltv --force-export --verbose 

# Update the Combiner-channels as well.
$d perl -I lib tools/nonametv-import Combiner $Q
$h perl -I lib tools/nonametv-import Combiner --short-grab $Q

$d perl -I lib tools/nonametv-import Timeshifter $Q
$h perl -I lib tools/nonametv-import Timeshifter --short-grab $Q

tools/se/nonametv-updatesite $Q

$d tools/se/nonametv-xmltv-compare-run
perl -I lib tools/nonametv-batchlog > /srv/web/converter.xmltv.se/root/status/batchlog.html

