#!/bin/sh

# NONAMETV=nonametv-import
NONAMETV="perl -I lib/ tools/nonametv-import"

$NONAMETV Kanal5_http $1 $2 $3
$NONAMETV Viasat $1 $2 $3
$NONAMETV TV4 $1 $2 $3
$NONAMETV Svt $1 $2 $3
$NONAMETV CanalPlus $1 $2 $3
$NONAMETV Mtve $1 $2 $3
$NONAMETV Nonstop $1 $2 $3
$NONAMETV Aftonbladet_http $1 $2 $3
$NONAMETV NASN $1 $2 $3
$NONAMETV DR $1 $2 $3
