#!/bin/sh

NROOT=/var/local/nonametv

tools/nonametv-export Xmltv --export-channels $1 $2 $3
tools/nonametv-export Xmltv $1 $2 $3
tools/nonametv-export Json --export-channels $1 $2 $3
tools/nonametv-export Json $1 $2 $3

tools/se/nonametv-xmltv-genhtml $NROOT/xmltv_staging .

tools/se/nonametv-upload $1 $2 $3
