#!/bin/sh

# NONAMETV=nonametv-import
NONAMETV="tools/nonametv-import"

$NONAMETV Kanal5 $1 $2 $3
$NONAMETV Kanal9 $1 $2 $3
$NONAMETV Viasat $1 $2 $3
$NONAMETV Viasat_dev $1 $2 $3
$NONAMETV TV4 $1 $2 $3
$NONAMETV Svt $1 $2 $3
$NONAMETV CanalPlus $1 $2 $3
$NONAMETV CanalPlusPPV $1 $2 $3
$NONAMETV Mtve $1 $2 $3
$NONAMETV Nonstop $1 $2 $3
$NONAMETV NASN $1 $2 $3
$NONAMETV DR $1 $2 $3
$NONAMETV Axess $1 $2 $3
$NONAMETV SverigesRadio $1 $2 $3
$NONAMETV Eurosport $1 $2 $3
