#!/bin/bash

if [ "x$1" == "x" ]; then
echo "nonametv-import-svt <xmlfile>"
echo
echo "Import a datafile from Svt into the nonametv database."
echo 
exit
fi

awk 'BEGIN { p=0 } /^</ {p=1} p==1 {print}' $0 | xsltproc - $1 | nonametv-import Svt
exit
<?xml version="1.0" encoding="iso-8859-1"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:output method="xml" indent="no"/>

  <xsl:template match="schedule">
     <schedule>
     <xsl:copy-of select="@*"/>
     <xsl:apply-templates/>
     </schedule>
  </xsl:template>

  <xsl:template match="programs">
     <programs>
     <xsl:copy-of select="@*"/>
     <xsl:apply-templates select="program">
       <xsl:sort select="normalize-space(week_number/text())"/>
       <xsl:sort select="normalize-space(channel/text())"/>
     </xsl:apply-templates>
     </programs>
  </xsl:template>

  <xsl:template match="*">
    <xsl:copy-of select="."/>
  </xsl:template>

</xsl:stylesheet>