#!/bin/sh

# NONAMETV=nonametv-import
NONAMETV="perl -I lib/ tools/nonametv-import"

$NONAMETV Viasat $1 $2 $3
$NONAMETV CanalPlus $1 $2 $3
$NONAMETV Infomedia $1 $2 $3
$NONAMETV Nonstop $1 $2 $3
$NONAMETV TV2 $1 $2 $3
$NONAMETV NRK $1 $2 $3
$NONAMETV DiscoveryScraper $1 $2 $3
