#!/usr/bin/perl -w

use strict;

use NonameTV;
use NonameTV::DataStore;
use NonameTV::Config qw/ReadConfig/;

use Getopt::Long;

# Read configuration
my $conf = ReadConfig();

# Create Datastore
my $ds = NonameTV::DataStore->new( $conf->{DataStore} );

print "Clearing all listings from database\n";
$ds->sa->Delete( "batches", {} );
$ds->sa->Delete( "programs", {} );
$ds->sa->Delete( "state", {} );

