#!/usr/bin/perl -w

use strict;

use FindBin;
use lib "$FindBin::Bin/../lib";

use NonameTV::Factory qw/CreateDataStore CreateDataStoreDummy 
                         CreateExporter InitLog InitHttpCache/;

use Getopt::Long;

InitLog();

my $ds = CreateDataStore();

my $exp_name = shift @ARGV;
my $exp = CreateExporter( $exp_name, $ds );

my %opt = %{$exp->{OptionDefaults}};
my $option_spec = $exp->{OptionSpec};

my $res = GetOptions( \%opt, @{$option_spec} );

# Run exporter
$exp->Export( \%opt );

