#!/bin/sh

NROOT=/var/local/nonametv
SC_OPT=-qq
VALIDATE_OPT=

if [ $1z = '--verbosez' ]
then
  SC_OPT=
fi

perl -I lib/ tools/nonametv-export Xmltv $1 $2 $3

tools/nonametv-xmltv-genhtml $NROOT/xmltv_staging
perl -I lib tools/nonametv-batchlog > /var/local/nonametv/xmltv_compare/00status.html

rsync -c --delete -r $NROOT/xmltv_staging/ $NROOT/xmltv/
sitecopy --update $SC_OPT tv.swedb.se

