#!/bin/bash

NROOT=/var/local/nonametv
PROOT=/home/mattias/development/nonametv

h=true
d=true

cd $PROOT

if [ $1x = --weeklyx ]
then
  # Run weekly commands.
  perl -I lib tools/nonametv-remove-old
  exit
fi

if [ $1x = --dailyx ]
then
  # Run daily commands
  d=
fi

if [ $1x = --hourlyx ]
then
  # Run hourly commands
  h=
fi

$d tools/nonametv-import-allhttp
$h tools/nonametv-import-allhttp --short-grab
tools/nonametv-import-maildir

$d perl -I lib/ tools/nonametv-export Xmltv --remove-old

tools/nonametv-updatesite

# This shouldn't produce any output, but there seems to be a bug
# somewhere.
$d perl -I lib tools/nonametv-export Xmltv --force-export --verbose 2>&1 | grep -v INFO

# Update the Combiner-channels as well.
$d perl -I lib tools/nonametv-import Combiner
$h perl -I lib tools/nonametv-import Combiner --short-grab

tools/nonametv-xmltv-genhtml $NROOT/xmltv_staging

tools/nonametv-updatesite

$d tools/nonametv-xmltv-compare-run
