#!/usr/bin/perl -w

use strict;

use NonameTV;
use NonameTV::DataStore::Dummy;
use NonameTV::Config qw/ReadConfig/;

use Getopt::Long;

# Read configuration
my $conf = ReadConfig();

# Create Datastore
my $ds = NonameTV::DataStore::Dummy->new( $conf->{DataStore} );

# Create the right importer
my $imp_name = shift @ARGV;
my $contentname = shift @ARGV;
my $filename = shift @ARGV;
print "Content: $contentname\nFile: $filename\n";

my $imp_data = $conf->{Importers}->{$imp_name};
my $imp_type = $imp_data->{Type};

my $imp = eval "use NonameTV::Importer::$imp_type; 
                NonameTV::Importer::${imp_type}->new( \$imp_data, \$ds );"
        or die $@;

my %opt = eval "\%NonameTV::Importer::${imp_type}::OptionDefaults";
my $option_spec = eval "\$NonameTV::Importer::${imp_type}::OptionSpec";

my $res = GetOptions( \%opt, @{$option_spec} );

# Run importer
$imp->ImportFile( $contentname, $filename, \%opt );
