#!/usr/bin/perl -w

use strict;

use NonameTV::XmltvValidate qw/xmltv_validate_file/;
use Getopt::Long;

my $p = { verbose => 0 };

my $res = GetOptions( $p, qw/verbose/ );

if( scalar(@ARGV) == 0 )
{
  print << "EOD";
tv_validate [xmltv-file]...

Validate one or several xmltv-files and check the following:

Each file is valid xml.
Each file conforms to the xmltv-dtd.
Each programme has a valid channel identifier.
Each programme has a valid start and stop-time.
Each programme has a non-empty title.
Stop-time is strictly later than start-time for each programme.
No programmes overlap.

tv_validate assumes that the input-file is already sorted by channel and
start-time.

EOD

  exit(1);
}

my $outf=sub {
    my( $file, $line, $err ) = @_;
    print "$file $line: $err\n";
  };

foreach my $file (@ARGV)
{
  my $doc;

  print "Validating $file\n" if $p->{verbose};
  my $errors = xmltv_validate_file( $file, $outf );
  print "$errors errors found.\n" if $errors or $p->{verbose};
}
